// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaTP3YOADOpIr2MYVLu0JhsQPrwfTyb28',
    appId: '1:850056925598:web:1a1683c153938471df068f',
    messagingSenderId: '850056925598',
    projectId: 'pushnotification-7f95c',
    authDomain: 'pushnotification-7f95c.firebaseapp.com',
    storageBucket: 'pushnotification-7f95c.appspot.com',
    measurementId: 'G-C99PS2T8JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCakDe4fIJuEm4kXrrFtI6R0nMHqdbbq3M',
    appId: '1:850056925598:android:948c31f02c5596a1df068f',
    messagingSenderId: '850056925598',
    projectId: 'pushnotification-7f95c',
    storageBucket: 'pushnotification-7f95c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNQYShIb1eFROWri2-ypjCjqEOLXfJrbM',
    appId: '1:850056925598:ios:16ff28fd811d119cdf068f',
    messagingSenderId: '850056925598',
    projectId: 'pushnotification-7f95c',
    storageBucket: 'pushnotification-7f95c.appspot.com',
    iosBundleId: 'com.example.flutternotification',
  );
}
