// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWiokirMl0l-_MmwBPdZrr7xuAjtxLfvM',
    appId: '1:759770326633:web:dd34da7623426bc79ee4f8',
    messagingSenderId: '759770326633',
    projectId: 'notification-245e7',
    authDomain: 'notification-245e7.firebaseapp.com',
    storageBucket: 'notification-245e7.appspot.com',
    measurementId: 'G-S9L4FZ4KCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf_qhWIX1Afd1-kcz8PjIZRgMA0j-GIJA',
    appId: '1:759770326633:android:599253f88637114e9ee4f8',
    messagingSenderId: '759770326633',
    projectId: 'notification-245e7',
    storageBucket: 'notification-245e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGS9JpVUAdPRRuYm022p4odsBcStNgTug',
    appId: '1:759770326633:ios:7160ba57e4c606569ee4f8',
    messagingSenderId: '759770326633',
    projectId: 'notification-245e7',
    storageBucket: 'notification-245e7.appspot.com',
    iosBundleId: 'com.example.flutternotification',
  );
}
